### ISSUE TITLE
IOS APP CRASH

### ISSUE THREAD

**Issue by searoopy** [YoYoGames/GMEXT-FMOD#13]
### Description

voice record sample code is App crashes(without any error message)  on iPhone 13 mini

iphone 14 pro working fine

Both iPhones OS are up to date

FMOD is 0.0.8

GMS 2024.6.2.162

### Steps To Reproduce

1. Start GameMaker
2. iphone build 
3. test iphone14pro , iphone13 mini
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Monthly

### Which platform(s) are you seeing the problem on?

iOS

### Compiler Log File

- [X] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by DiasFranciscoA** [comment]
Thank you for reaching out to us, 

we don't have a way to test this in a iphone 13 mini... I would like to get more information if possible to narrow the location of the bug could you place some `show_debug_message` in different places of the code of the demo to check what call to the C++ extension is causing the issue? thank you

**Comment by DiasFranciscoA** [comment]
@searoopy I'll mark this as not planned, until we have further information. Please add more information and reopen the ticket
