### ISSUE TITLE
Build fails when trying to get a user property

### ISSUE THREAD

**Issue by PheonixMetal** [YoYoGames/GMEXT-FMOD#14]
### Description

Version: v2024.6.2.162 Runtime v2024.6.1.208 (tried attaching a YYZ but don't see where to do so)

[GM FMOD Error Output.txt](https://github.com/user-attachments/files/16745442/GM.FMOD.Error.Output.txt)

[Rhythm System.zip](https://github.com/user-attachments/files/16767927/Rhythm.System.zip)

I am attempting to get User Properties for events that I've set up, but the build says it failed and I pinpointed the exact function:
![image](https://github.com/user-attachments/assets/e84c72ef-0a02-4651-9bf3-a954326e7cd0)
If I Build my FMOD Studio project in order to get the properties, I use `fmod_studio_event_description_get_user_property()` which gets me a build error directly at line 2233 where the function `fmod_studio_event_description_get_user_property_multiplatform()` is called. This is a function that doesn't lead me to anywhere documented or within the projects functions.

The value I tried to get from user properties was BPM = 140.

I've put a break point directly on this function and if you continue from there the build immediately fails and goes no further.

### Expected Change

A fix for the build error you get when trying to get user properties from FMOD Studio events.

### Steps To Reproduce

1. Start GameMaker
2. Open the project provided
3. Run the project
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Monthly

### Which platform(s) are you seeing the problem on?

Windows

### Compiler Log File

- [X] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by DiasFranciscoA** [comment]
The error you are seeing is NOT a build error.. is a runtime (execution) error, the game is build properly and runs correctly the problem occurs when trying to execute the function `fmod_studio_event_description_get_user_property` the other function you are seeing is an internal function that shouldn't be changed or called directly. We will look at the bug and get back to you as soon as possible with a proper fix.

> [!WARNING]
> We never post fixes here in the comments, never download anything posted here marked as a fix. Proper fixes are addressed by us with a new release. Never download or run any software from the comment section.

**Comment by DiasFranciscoA** [comment]
@PheonixMetal we just noticed that no project was attached in the original bug report.
Please if possible make sure you include a repro project so we can investigate the issue.

**Comment by PheonixMetal** [comment]
> @PheonixMetal we just noticed that no project was attached in the original bug report. Please if possible make sure you include a repro project so we can investigate the issue.

Sorry about that, how would you like me to attach it? I tried to upload a zip with the yyz but that didn't work.

**Comment by DiasFranciscoA** [comment]
Fixed in b091c0befba5af411f543effff243957cdfc1009

The release is already up on github (0.0.9)
