### ISSUE TITLE
FMod Extension: [iOS] Terrible problems streaming if you select Net Stream

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GMEXT-FMOD#16]
### Which Extension are you reporting this issue for?

FMOD

### Description

It is notable that building this demo project for IOS does function, but has terrible problems streaming if you select Net Stream 

(Windows has no such issue)

_Split off from https://github.com/YoYoGames/GameMaker-Bugs/issues/8391_

### Expected Change

The demo should function the same on all platforms

### Steps To Reproduce

1. Start GameMaker and import/open the FMOD demo project
2. Run it for iOS
3. Use the net stream test
4. See/hear the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.8.1 (Monthly)

### Which platform(s) are you seeing the problem on?

iOS

### Sample Package Attached?

- [ ] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
Issue will be closed and 2 feature requests will be created, please refer to: https://github.com/YoYoGames/GMEXT-FMOD/issues/15
