### ISSUE TITLE
Add tvOS support to the FMOD extension

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GMEXT-FMOD#18]

**Comment by peardox** [comment]
I've almost got this working with tvOS but I'm getting a linker error

Building for 'tvOS', but linking in object file (fmodtesttvoswin/Game/tvOSSource/libYYFMOD.a[2](Fmod_Studio_System.o)) built for 'iOS'

I copied fmod_ios -> fmod_tvos then changed the libraries to the correct ones (libfmodL_appletvos.a + libfmodstudioL_appletvos.a) but when linking with the demo project I get the error above linking to Fmod_Studio_System.o - can't find why that's building for iOS when I explicityly built for tvOS in tvOSSource/libYYFMOD.a

**Comment by peardox** [comment]
Wow - cxan't wait to give it a go

Thanks a million

**Comment by peardox** [comment]
@DiasFranciscoA 
Ahh - Needs a tvOSSource folder and libYYFMOD.a in it

Built and sent to TestFlight (taking forever as usual...)
