### ISSUE TITLE
Game immediately crashes on launch most of the time, but runs with no issue other times

### ISSUE THREAD

**Issue by gjoyner** [YoYoGames/GMEXT-FMOD#8]
### Description

Unfortunately, I'm not sure what the issue is. I made a change in my FMOD project, simply swapping out which files a multi-instrument was using for a couple of events, and suddenly the game crashes immediately after starting almost every launch. It used to crash every now and then, but now it's far more rare for it to run. When it does start running, it works fine with no issue. Rebuilding the banks and cleaning the GMS project do not resolve the issue.

Any ideas of what all I can check? Any extra logs to enable?
[gmext_fmod_log.txt](https://github.com/YoYoGames/GMEXT-FMOD/files/15205615/gmext_fmod_log.txt)

### Steps To Reproduce

1. Start GameMaker
2. Run the project with FMOD Studio flags set to Normal
3. Wait for game to run
4. Game "exited with non-zero status" very likely happens.

### How reliably can you recreate this issue using your steps above?

Most Times

### Which version of GameMaker are you reporting this issue for?

Monthly

### Which platform(s) are you seeing the problem on?

Windows

### Compiler Log File

- [X] I have attached my compiler log in a text file

### Sample .yyz File

- [x] I have attached a small sample project

**Comment by gjoyner** [comment]
I did some more digging and I discovered that it is, in fact, the 2 events that I edited in FMOD Studio that are causing the crashes. Here's are the details:

- I have 2 nearly identical events. The 2nd one may have been created by duplicating the first event and then modifying it in Studio (don't quite remember).
- Track 1 is a multi-instrument consisting of 2 single instruments. The single instruments are using a .wav asset.
- Track 2 is a snapshot instrument targeting a specific return channel. The snapshot intensity is automated to the timeline.
- The crashes started after I changed the files in the single instruments:
- 1. I selected the multi-instrument and clicked Clear.
- 2. I added 2 single instruments.
- 3. I set each instrument to a new .wav asset.
- 4. I adjusted the timing of both tracks.
- 5. Rebuilt and moved the banks to GMS.
- 6. The game appears to be crashing when `fmod_studio_system_update` is called any point after an instance of one of these events is created. Both instance creations has a status of OK.
- NOTE: Creating new events using the same setup but different .wav files works correctly. The files causing the problem have been attached in a zip file.
![image](https://github.com/YoYoGames/GMEXT-FMOD/assets/3464327/4f73433a-9555-4d45-beed-f2a8d777534f)
[scratches.zip](https://github.com/YoYoGames/GMEXT-FMOD/files/15206010/scratches.zip)

**Comment by gjoyner** [comment]
Just discovered something else. The crash only seems to occur when both of the files in the zip are loaded at the same time, regardless of whether they are in the same event or 2 different events. If only 1 of the 2 files is loaded, it will run, but usually crashes on the first run and is fine after that.

**Comment by gjoyner** [comment]
Did some more digging and I have an example project that is similar to the issue that I'm having. Here's a few things of note:

- The zip file contains the FMOD project "gmext_fmod_issue" and the GMS project "FMOD Ext Issue".
- It appears to be related to loading the banks. On the example project, loading the bank holding the problemed events with NONBLOCKING allows the project to load. If set to NORMAL, the game will crash immediately.
- Even with NONBLOCKING, click the "Alt" button and it should crash.
- During one of my attempts to run this GMS test project, it briefly popped up with an error relating to buses, but I didn't grab the error before moving on (really should have, as it didn't happen again after that). I think I saw a similar error with the game I'm working on.
- In my actual project, loading the bank with NONBLOCKING did not prevent crashing.

Let me know if I can be of any assistance!
[FMOD Ext Issue.zip](https://github.com/YoYoGames/GMEXT-FMOD/files/15211559/FMOD.Ext.Issue.zip)
[gmext_fmod_issue.zip](https://github.com/YoYoGames/GMEXT-FMOD/files/15211561/gmext_fmod_issue.zip)

**Comment by DiasFranciscoA** [comment]
Morning @gjoyner,

We were able to replicate this very unstable issue. We will push an update soon (TM) probably even today.

Thank you for reporting the issue.

**Comment by DiasFranciscoA** [comment]
Updated and fixed on v0.0.4

**Comment by gjoyner** [comment]
It appears to be working on my project. Thank you for the quick fix!
